# Starter pipeline
- task: IBMIntegrationBusCommand@1
  inputs:
    connType: 'address'
    integrationNodeName: 'TESTNODE'
    ipAddress: 'ec2-16-171-17-112.eu-north-1.compute.amazonaws.com'
    cmd: 'mqsilist'
    args: 'TESTNODE'

# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'

- task: IBMIntegrationBusDeploy@1 
  inputs:
    barPath: 'TestBar.bar'
    connType: 'address'
    integrationNodeName: 'INODE'
    ipAddress: 'localhost'
    integrationServerName: 'ISERVER'
    completeDeployment: true